### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by beiji-O-o** [Yoruwu/pyrogramsessiongen#1]
![image](https://github.com/Yoruwu/pyrogramsessiongen/assets/100279019/fe897ed4-5ee5-48f7-8e29-72621a8bb1d9)
Hello developer, how can I resolve this error?

**Comment by Yoruwu** [comment]
Sup! It could be a Telegram rate limit or something... try with a VPN. If you still get that problem please let me know :)

Also keep in mind, if you mess up ur login to many times you get blocked for a bit.

**Comment by Yoruwu** [comment]
**can't reproduce**
